#Config
#Sun Apr 05 13:18:08 MSK 2026
commentTableColumn.width=101.0
companyTableColumn.width=127.0
console.visible=false
database.path=D\:\\Projects\\database.bin
dateOfLastWorkTableColumn.width=159.0
dateOfSendToArchive.width=106.0
db.save.on.close=true
db.load.on.start=false
frameCreateDateTableColumn.width=127.0
managerTableColumn.width=139.0
nameTableColumn.width=124.0
numberOfLayoutTableColumn.width=176.0
statusOfFrameTableColumn.width=86.0
theme=Catppuccin latte
typeOfFrameTableColumn.width=106.0
window.height=922.0
window.maximized=false
window.width=1743.0
window.x=585.0
window.y=217.0
